// PHASE 3 STEP 28
// PHASE 3 STEP 29
export const APP_CONFIG = {
  // PHASE 4 STEP 26
  TEST_MODE: false,
  REQUIRE_EMAIL_VERIFICATION: false,
  CLAIM_VOTING_MODE: "production",
  TEST_VOTE_CLOSE_MINUTES: 10,
  TEST_SCORE_LOCK_MINUTES: 15,
  TEST_EXPIRES_MINUTES: 15,
  TEST_MIN_VOTES_REQUIRED: 5,
  TEST_EXPECTED_PARTICIPATION: 10,
} as const;
