import type { Metadata } from "next";

import { LegalPage } from "@/components/navigation/legal-page";

export const metadata: Metadata = { title: "Privacy policy | FactFight", description: "How FactFight and Verifact handle account and community data." };

export default function PrivacyPage() {
  return <LegalPage effective="Effective June 10, 2026" title="Privacy policy"><section><p>FactFight is the web experience for Verifact, a community-powered claim verification service operated by PennyFloat. This policy explains how the service collects, uses, stores, and protects information for accounts, claims, evidence, voting, reports, moderation, and AI-assisted analysis.</p><p className="mt-3">PennyFloat does not sell personal data.</p></section><section><h2>Information we collect</h2><ul><li>Account information such as email address, username, display name, authentication identifiers, profile details, and account status.</li><li>Claim text, source URLs, uploaded images, evidence notes, votes, reports, and other user submissions.</li><li>Moderation, safety, reputation, and trust signals including report status, visibility status, vote history, badges, and account action records.</li><li>Technical information such as browser details, diagnostics, cookies, local storage, network data, and service logs.</li></ul></section><section><h2>How we use information</h2><ul><li>To authenticate users, maintain profiles, provide support, and process account requests.</li><li>To publish and operate claims, evidence, votes, reports, and public contributor pages.</li><li>To investigate abuse, enforce policies, prevent spam, and protect service integrity.</li><li>To operate diagnostics, reliability monitoring, security checks, and product improvements.</li></ul></section><section><h2>AI-assisted analysis</h2><p>The service may use AI-assisted systems to classify, summarize, and evaluate claims, source URLs, evidence, and related context. AI outputs are preliminary risk signals and may be wrong, incomplete, outdated, or biased. AI never makes the final community verdict.</p></section><section><h2>Service providers</h2><p>The service uses providers including Supabase for authentication, database, and storage; Render for backend hosting; and delivery, logging, email, security, and moderation providers as needed to operate the platform.</p></section><section><h2>Public content and retention</h2><p>Claims, evidence, votes, public profile details, and reputation signals may be visible to other users. Information is retained as needed to operate the service, comply with law, resolve disputes, prevent abuse, and preserve verification history.</p></section><section><h2>Contact</h2><p>For privacy questions, support, or account deletion requests, contact <a href="mailto:support@factfight.com">support@factfight.com</a>.</p></section></LegalPage>;
}
