import type { Metadata } from "next";

import { LegalPage } from "@/components/navigation/legal-page";

export const metadata: Metadata = { title: "Terms of use | FactFight", description: "Terms governing use of FactFight and the Verifact community platform." };

export default function TermsPage() {
  return <LegalPage effective="Last updated July 2026" title="Terms of use"><section><h2>Acceptance</h2><p>By creating an account or using FactFight or Verifact, you agree to these Terms of Use. If you do not agree, do not use the service.</p></section><section><h2>Zero tolerance for objectionable content</h2><p>The service has zero tolerance for objectionable content and abusive users. Prohibited content includes harassment, hate speech, threats, sexually explicit material, content that exploits or endangers minors, spam, impersonation, and deliberate targeted abuse.</p></section><section><h2>Your content</h2><p>You are responsible for claims, evidence, reports, profile information, and other content you submit. You retain ownership subject to third-party rights and grant PennyFloat a worldwide, non-exclusive, royalty-free license to host, store, display, analyze, moderate, format, and distribute that content as needed to operate and protect the service.</p><p className="mt-3">You may remove a claim within 3 hours of posting. After that, or after a verdict is finalized, the claim becomes part of the permanent verification record. Account deletion may anonymize rather than remove public contributions when needed to preserve that record.</p></section><section><h2>Community verdicts and AI</h2><p>Verdicts are produced through community voting and evidence review. AI is used only as a risk signal and never as the final judge. Results are informational, may be incorrect, and are not legal, medical, financial, election, safety, or other professional advice.</p></section><section><h2>Fair participation</h2><p>Vote manipulation, multiple accounts used to influence verdicts, fabricated sources, impersonation, scraping, malicious links, credential abuse, rate-limit evasion, and attempts to interfere with service operations are prohibited.</p></section><section><h2>Moderation</h2><p>PennyFloat may review, label, limit, hide, remove, or preserve content and may suspend or terminate accounts to enforce these terms, protect users, investigate abuse, comply with law, or maintain service integrity.</p></section><section><h2>Limitation</h2><p>To the fullest extent permitted by law, PennyFloat is not liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost data, service interruption, reputational harm, or reliance on user-generated or AI-assisted content.</p></section><section><h2>Contact</h2><p>Questions about these terms may be sent to <a href="mailto:support@factfight.com">support@factfight.com</a>.</p></section></LegalPage>;
}
